config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :messages
  resources :doors
  resources :event_instances
  resources :events
  resources :heroes
  resources :levels
  resources :games
  resources :heroes
  resources :packages
  resources :doors
  resources :users
  resources :gamestates
  resources :sessions
  get  '/gamestate', to: 'gamestates#save'
  get 'main/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main#index'
  #post 'levels/doors', to: 'levels#doors'
  get   'level-doors/:id', to: 'levels#doors'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  get '/event_instances/:id/:choice', to: 'event_instances#show'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/gamestates/reset/:id', to: 'gamestates#reset'
  get '/gamestates/partial/:id', to: 'gamestates#partial'
  get '/games', to: 'games#index'
  get '/discussion', to: 'messages#discussion'
  post '/discussion', to: 'message#create'
  get '/addtopic', to: 'topics#new'
  get '/topic/:id', to: 'topics#show', as: 'joindiscuss'
  get '/publishedgames', to: 'games#published'
  get '/doors/open/:id', to: 'doors#open'
  #game creation
  get '/creategame', to: 'games#new'
  get '/allgames', to: 'games#all'
  get '/barload', to: 'games#barload'
  get '/addlevel/:game_id' , to: 'levels#new', as: 'addlevel'
  get '/addevent/:game_id' , to: 'events#new', as: 'addevent'
  get '/adddoor/:game_id' , to: 'doors#new', as: 'adddoor'
  get '/addhero/:gamestate_id' , to: 'heroes#new', as: 'addhero'

  get 'editevent/:game_id/:id', to: 'events#edit', as: 'editevent'
  get 'editlevel/:game_id/:level_id', to: 'levels#organizeevents', as: 'editlevel'
  get 'editdoor/:game_id/:id', to: 'doors#edit', as: 'editdoor'

  get '/assigneventforone/:game_id/:level_id', to: 'levels#assigneventforone', as: 'assigneventforone'
  get '/queueevent/:game_id/:level_id/:event_id', to: 'levels#queueevent', as: 'queueevent'
  get '/dequeueevent/:game_id/:level_id', to: 'levels#dequeueevent', as: 'dequeueevent'

  get '/assigndoorforone/:game_id/:level_id', to: 'levels#assigndoorforone', as: 'assigndoorforone'
  get '/queuedoor/:game_id/:level_id/:door_id', to: 'levels#queuedoor', as: 'queuedoor'
  get '/dequeuedoor/:game_id/:level_id', to: 'levels#dequeuedoor', as: 'dequeuedoor'

  get '/assignlevelforone/:game_id/:door_id', to: 'doors#assignlevelforone', as: 'assignlevelforone'
  get '/queuelevel/:game_id/:door_id/:level_id', to: 'doors#queuelevel', as: 'queuelevel'
  get '/dequeuelevel/:game_id/:door_id', to: 'doors#dequeuelevel', as: 'dequeuelevel'

  #get '/assigneventforall/:game_id', to: 'levels#assigneventforall', as: 'assigneventforall'
  get '/creategamelogic/:game_id', to: 'levels#creategamelogic', as: 'creategamelogic'
  get '/organize/:game_id' , to: 'levels#organize', as: 'organizelevel'
  get 'designatestart/:game_id', to: 'levels#designatestart', as: 'designatestart'
  get '/levels/dashboard/:game_id', to: 'levels#dashboard', as: 'leveldashboard'
  get '/startinglevel/:game_id/:level_id', to: 'games#startinglevel', as: 'startinglevel'

  get '/initiatehero/:game_id', to: 'gamestates#initiate', as: 'initiate'

  #search routets

  post '/searchtopic', to: 'topics#search'
  get '/searchtopic', to: 'topics#search'

  get '/review/:game_id', to: 'games#review', as: 'review'

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  after_create_commit { 
  	MessageBroadcastJob.perform_later(self)
  }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  include SessionsHelper
  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  def discussion
    @curruser = current_user
    @messages = Message.all
    @message = Message.new
    @topics = Topic.all
   
    @ratetopics = Topic.where(topictype: "Rate the game")
    @strategytopics = Topic.where(topictype: "Game strategy")
    @questiontopics = Topic.where(topictype: "Questions about the Game")
    
    render 'discussion'
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)
    
    @message.user = current_user
    @message.save
    @topic_id = message_params[:topic_id]
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    Message.find(params[:id]).destroy
  	  respond_to do |format|
	    format.js { render "destroy", :locals => {:id => params[:id]} }
	  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:body, :topic_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<%= stylesheet_link_tag 'topics' %>

<div  id="message_<%=message.id%>">
<div class="chat_container darker">
	[<%= message.created_at.strftime("%l:%M %p") %>] <%= message.user.name.split('@')[0].capitalize %>: <%= message.body %>
</div>
</div>

app/views/messages/create.js.erb
$('#chatbox_' + <%= @topic_id %>).append("<%= j render @message %>");
$('#message_body').val('');

app/views/messages/discussion.html.erb
<h1 style = "text-align:center">Discussion Page</h1>
<% if @curruser %>
<h2 style = "text-align:center">Hi welcome to game discussion forum <%=  @curruser.name %></h2>
<%end %>

  
<div class="d-flex justify-content-center">
    <%= link_to "Add Topic", addtopic_path, class:"btn btn-lg btn-createtopic" %>
</div>


<div id="exTab2" class="container">	
<ul class="nav nav-tabs">
			<li class="active">
        <a  href="#1" data-toggle="tab">Rate the game</a>
			</li>
			<li><a href="#2" data-toggle="tab">Game strategy</a>
			</li>
			<li><a href="#3" data-toggle="tab">Question about game</a>
           
		</ul>

			<div class="tab-content ">
			  <div class="tab-pane active" id="1">
             
              <% Topic.where(topictype: "Rate the game").each do |topic| %>
                <div class="gs-row-2-col">
                <div class="gs card">
                  <% if topic.topic_image.blank? %>
                    <%= image_tag("defaultgame.png", :height =>"180", :width => "260")%>
                  <% else %>
                      <%= image_tag(topic.topic_image, :height =>"180", :width => "260")%>
                  <% end %>
                  <div class="gs card-body">
                    <h3 class="gs card-title"><%= topic.name %></h3>
                    <% if topic.description.blank? %>
                      <h4 class="gs card-text">No description</h4>
                    <% else %>
                      <h4 class="gs card-text"><%= topic.description %></h4>
                    <% end %>
                    <%= link_to "Join", joindiscuss_url(topic.id), class: "btn-card" %>
                    
                  </div>
                </div>
              </div>
              <% end %>
				</div>
                <div class="tab-pane" id="2"> 
                    <% Topic.where(topictype: "Game strategy").each do |topic| %>
                        <div class="gs-row-2-col">
                        <div class="gs card">
                          <% if topic.topic_image.blank? %>
                            <%= image_tag("defaultgame.png", :height =>"180", :width => "260")%>
                          <% else %>
                              <%= image_tag(topic.topic_image, :height =>"180", :width => "260")%>
                          <% end %>
                          <div class="gs card-body">
                            <h3 class="gs card-title"><%= topic.name %></h3>
                            <% if topic.description.blank? %>
                              <h4 class="gs card-text">No description</h4>
                            <% else %>
                              <h4 class="gs card-text"><%= topic.description %></h4>
                            <% end %>
                            <%= link_to "Join", joindiscuss_url(topic.id), class: "btn-card" %>
                            
                          </div>
                        </div>
                      </div>
                    <% end %>
				</div>
            <div class="tab-pane" id="3">
           
            <% Topic.where(topictype: "Questions about the Game").each do |topic| %>
                <div class="gs-row-2-col">
                <div class="gs card">
                  <% if topic.topic_image.blank? %>
                    <%= image_tag("defaultgame.png", :height =>"180", :width => "260")%>
                  <% else %>
                      <%= image_tag(topic.topic_image, :height =>"180", :width => "260")%>
                  <% end %>
                  <div class="gs card-body">
                    <h3 class="gs card-title"><%= topic.name %></h3>
                    <% if topic.description.blank? %>
                      <h4 class="gs card-text">No description</h4>
                    <% else %>
                      <h4 class="gs card-text"><%= topic.description %></h4>
                    <% end %>
                    <%= link_to "Join", joindiscuss_url(topic.id), class: "btn-card" %>
                    
                  </div>
                </div>
              </div>
            <% end %>
            </div>
           
           
			</div>
  </div>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/forumpage.html.erb
<h1>Game discussion</h1>
<%= form_for @message, remote: true do |form| %>
    <div id="msg">

    </div>
    
    <%= form.label :content %>
    <%= form.text_area :content %>

    <div class="actions">
    <%= form.submit %>
    </div>
<% end %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>