config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :messages
  resources :doors
  resources :event_instances
  resources :events
  resources :heroes
  resources :levels
  resources :games
  resources :heroes
  resources :packages
  resources :doors
  resources :users
  resources :gamestates
  resources :sessions
  get  '/gamestate', to: 'gamestates#save'
  get 'main/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main#index'
  #post 'levels/doors', to: 'levels#doors'
  get   'level-doors/:id', to: 'levels#doors'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  get '/event_instances/:id/:choice', to: 'event_instances#show'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/gamestates/reset/:id', to: 'gamestates#reset'
  get '/gamestates/partial/:id', to: 'gamestates#partial'
  get '/games', to: 'games#index'
  get '/discussion', to: 'messages#discussion'
  post '/discussion', to: 'message#create'
  get '/addtopic', to: 'topics#new'
  get '/topic/:id', to: 'topics#show', as: 'joindiscuss'
  get '/publishedgames', to: 'games#published'
  get '/doors/open/:id', to: 'doors#open'
  #game creation
  get '/creategame', to: 'games#new'
  get '/allgames', to: 'games#all'
  get '/barload', to: 'games#barload'
  get '/addlevel/:game_id' , to: 'levels#new', as: 'addlevel'
  get '/addevent/:game_id' , to: 'events#new', as: 'addevent'
  get '/adddoor/:game_id' , to: 'doors#new', as: 'adddoor'
  get '/addhero/:gamestate_id' , to: 'heroes#new', as: 'addhero'

  get 'editevent/:game_id/:id', to: 'events#edit', as: 'editevent'
  get 'editlevel/:game_id/:level_id', to: 'levels#organizeevents', as: 'editlevel'
  get 'editdoor/:game_id/:id', to: 'doors#edit', as: 'editdoor'

  get '/assigneventforone/:game_id/:level_id', to: 'levels#assigneventforone', as: 'assigneventforone'
  get '/queueevent/:game_id/:level_id/:event_id', to: 'levels#queueevent', as: 'queueevent'
  get '/dequeueevent/:game_id/:level_id', to: 'levels#dequeueevent', as: 'dequeueevent'

  get '/assigndoorforone/:game_id/:level_id', to: 'levels#assigndoorforone', as: 'assigndoorforone'
  get '/queuedoor/:game_id/:level_id/:door_id', to: 'levels#queuedoor', as: 'queuedoor'
  get '/dequeuedoor/:game_id/:level_id', to: 'levels#dequeuedoor', as: 'dequeuedoor'

  get '/assignlevelforone/:game_id/:door_id', to: 'doors#assignlevelforone', as: 'assignlevelforone'
  get '/queuelevel/:game_id/:door_id/:level_id', to: 'doors#queuelevel', as: 'queuelevel'
  get '/dequeuelevel/:game_id/:door_id', to: 'doors#dequeuelevel', as: 'dequeuelevel'

  #get '/assigneventforall/:game_id', to: 'levels#assigneventforall', as: 'assigneventforall'
  get '/creategamelogic/:game_id', to: 'levels#creategamelogic', as: 'creategamelogic'
  get '/organize/:game_id' , to: 'levels#organize', as: 'organizelevel'
  get 'designatestart/:game_id', to: 'levels#designatestart', as: 'designatestart'
  get '/levels/dashboard/:game_id', to: 'levels#dashboard', as: 'leveldashboard'
  get '/startinglevel/:game_id/:level_id', to: 'games#startinglevel', as: 'startinglevel'

  get '/initiatehero/:game_id', to: 'gamestates#initiate', as: 'initiate'

  #search routets

  post '/searchtopic', to: 'topics#search'
  get '/searchtopic', to: 'topics#search'

  get '/review/:game_id', to: 'games#review', as: 'review'

end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :name, presence: true, length: { maximum: 50 }
    # validates :topictype, presence: true
    has_many :messages
    has_one_attached :topic_image
    TYPE_LIST = ["Rate the game", "Game strategy", "Questions about the Game"]
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @curruser = current_user
    @messages = Message.all
    @message = Message.new
    @topics = Topic.all
   
  end

  # GET /topics/new
  def new
    @topic = Topic.new
    @games = Game.all
   
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
   
    if @topic.save
        @topics = Topic.all
        @messages = Message.all
        @curruser = current_user
       render 'messages/discussion'
    else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
    end
  
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def search
    @topics = Topic.where("name LIKE ?", "%#{params[:name]}%")
    render 'messages/discussion'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description, :topictype, :topic_image)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= stylesheet_link_tag 'creategame' %>

<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>
      <ul>
        <% topic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="cg-container">
  <div class='cg-row-1'>
    <h1>Create New Topic</h1>
  </div>
  <br>
  <div class="field">
      <%= form.label :name, class: 'game-form-control-label' %>
      <%= form.text_field :name,class: 'game-form-control-field' %>
  </div>

  <div class="field">
    <%= form.label :description, class: 'game-form-control-label' %>
    <%= form.text_field :description,class: 'game-form-control-field' %>
  </div>

  <div class="field">
      <%= form.label :topictype, class: 'game-form-control-label' %>
      <%= form.select :topictype, Topic::TYPE_LIST, class: 'game-form-control-field' %>
  </div>
 
  <div class="field">
      <%= form.label 'Upload a cover image:', class: 'game-form-control-label'%>
     
      <%= form.file_field :topic_image, class: 'game-form-control-field'%>
  </div>

  <div class="actions">
     <%= form.submit "Add the topic", class: "btn-creategame" %>
  </div>
  </div>
<% end %>

app/views/topics/_showtopics.html.erb
<% @topics.each do |topic| %>
    <%= topic.name %>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Game</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= topic.game_id %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<%= stylesheet_link_tag 'topics' %>
<p id="notice"><%= notice %></p>

<div class = "center textcenter jumbtron" style="background:#FFA500;">
<h1>
  <%= @topic.name %>
<h1>
</div>

 
<div class = "jumbtron" style="background:#FFE4B5;">

<h4 style="color:gray;"> <%= @topic.description %></h4>
<h4> <%= @topic.topictype %></h4>
<div class = "well center" id = "chatbox_<%= @topic.id %>" style = "height:300px; width:800px;  border: solid 1px #222222; overflow-y: scroll">
<% @messages.each do |message| %>
    <%if message.topic_id == @topic.id %>
   
       <%= render 'messages/message', message: message %>
  
    <% end %>
<% end %>
</div>
<% if @curruser %>
<%=  form_with model: @message do |f| %>
    <div class="input mb-3" style = "background: #FFE4B5">
        <%= f.hidden_field :topic_id, :value => @topic.id %>
        <br>
        <div class = "chatinput">
            <%= f.text_field :body, placeholder: "Input message then press Enter...", class:'form-control', autocomplete:'off' %>
        </div>
        
        <div class = "input center" style = "width:500px; " >
            <%= f.submit "Send", class: 'btn btn-lg btn-outline-secondary' %>
        </div>

    </div>
<% end %>
<% else %>
<p style = "text-align:center">
    You need to be <%= link_to"log in", login_path %> to chat.
</p>
<% end %>
</div>





<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back to Discussion', discussion_path %>