config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :messages
  resources :doors
  resources :event_instances
  resources :events
  resources :heroes
  resources :levels
  resources :games
  resources :heroes
  resources :packages
  resources :doors
  resources :users
  resources :gamestates
  resources :sessions
  get  '/gamestate', to: 'gamestates#save'
  get 'main/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main#index'
  #post 'levels/doors', to: 'levels#doors'
  get   'level-doors/:id', to: 'levels#doors'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  get '/event_instances/:id/:choice', to: 'event_instances#show'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/gamestates/reset/:id', to: 'gamestates#reset'
  get '/gamestates/partial/:id', to: 'gamestates#partial'
  get '/games', to: 'games#index'
  get '/discussion', to: 'messages#discussion'
  post '/discussion', to: 'message#create'
  get '/addtopic', to: 'topics#new'
  get '/topic/:id', to: 'topics#show', as: 'joindiscuss'
  get '/publishedgames', to: 'games#published'
  get '/doors/open/:id', to: 'doors#open'
  #game creation
  get '/creategame', to: 'games#new'
  get '/allgames', to: 'games#all'
  get '/barload', to: 'games#barload'
  get '/addlevel/:game_id' , to: 'levels#new', as: 'addlevel'
  get '/addevent/:game_id' , to: 'events#new', as: 'addevent'
  get '/adddoor/:game_id' , to: 'doors#new', as: 'adddoor'
  get '/addhero/:gamestate_id' , to: 'heroes#new', as: 'addhero'

  get 'editevent/:game_id/:id', to: 'events#edit', as: 'editevent'
  get 'editlevel/:game_id/:level_id', to: 'levels#organizeevents', as: 'editlevel'
  get 'editdoor/:game_id/:id', to: 'doors#edit', as: 'editdoor'

  get '/assigneventforone/:game_id/:level_id', to: 'levels#assigneventforone', as: 'assigneventforone'
  get '/queueevent/:game_id/:level_id/:event_id', to: 'levels#queueevent', as: 'queueevent'
  get '/dequeueevent/:game_id/:level_id', to: 'levels#dequeueevent', as: 'dequeueevent'

  get '/assigndoorforone/:game_id/:level_id', to: 'levels#assigndoorforone', as: 'assigndoorforone'
  get '/queuedoor/:game_id/:level_id/:door_id', to: 'levels#queuedoor', as: 'queuedoor'
  get '/dequeuedoor/:game_id/:level_id', to: 'levels#dequeuedoor', as: 'dequeuedoor'

  get '/assignlevelforone/:game_id/:door_id', to: 'doors#assignlevelforone', as: 'assignlevelforone'
  get '/queuelevel/:game_id/:door_id/:level_id', to: 'doors#queuelevel', as: 'queuelevel'
  get '/dequeuelevel/:game_id/:door_id', to: 'doors#dequeuelevel', as: 'dequeuelevel'

  #get '/assigneventforall/:game_id', to: 'levels#assigneventforall', as: 'assigneventforall'
  get '/creategamelogic/:game_id', to: 'levels#creategamelogic', as: 'creategamelogic'
  get '/organize/:game_id' , to: 'levels#organize', as: 'organizelevel'
  get 'designatestart/:game_id', to: 'levels#designatestart', as: 'designatestart'
  get '/levels/dashboard/:game_id', to: 'levels#dashboard', as: 'leveldashboard'
  get '/startinglevel/:game_id/:level_id', to: 'games#startinglevel', as: 'startinglevel'

  get '/initiatehero/:game_id', to: 'gamestates#initiate', as: 'initiate'

  #search routets

  post '/searchtopic', to: 'topics#search'
  get '/searchtopic', to: 'topics#search'

  get '/review/:game_id', to: 'games#review', as: 'review'

end

app/models/game.rb
class Game < ApplicationRecord
    has_many :levels
    has_many :events
    has_many :gamestates
    has_many :doors
    has_one_attached :game_image
    has_one_attached :graph_image
    validates :game_name, presence: true, length: { maximum: 50 }
    def self.search(search)
      if search
        where('game_name LIKE ? OR description LIKE ?',"%#{search}%","%#{search}%")
      else
        where("1=1")
      end
    end
end

app/controllers/games/graph.rb
module Games
    class Graph

        attr_accessor :game
        attr_accessor :start_level_id
        attr_accessor :levels
        attr_accessor :doors 

        def initialize(game, start_level_id, levels, doors, errors)
            @game = game
            @start_level_id = start_level_id
            @levels = levels
            @doors = doors
            @errors = errors
        end

        def valid
            g = GraphViz.new( :G, :type => :digraph)
            valid = true
            visited_door = Array.new
            visited_level = Array.new
            door_queue = Array.new
            level_queue = Array.new
            @errors = Array.new
            level_nodes = Hash.new
            @levels.each do |level|
                level_nodes[level.id] = g.add_nodes(level.name, :fontname => "Courier")
                visited_level[level.id] = false
            end
            door_nodes = Hash.new
            level_door_visit = Hash.new
            @doors.each do |door|
              door_nodes[door.id] = g.add_nodes(door.name, :shape => 'square', :fontname => "Courier")
              visited_door[door.id] = false
            end
            # Breadth first search with an extra step for doors
            if(!@start_level_id.nil?)
                level_queue.push(@start_level_id)
                while level_queue.length > 0
                    curr = level_queue.pop
                    if !(visited_level[curr])
                        visited_level[curr] = true
                        curr_level = @levels.find(curr)
                        next_doors = curr_level.doors
                        door_queue = JSON.parse(next_doors)
                        while door_queue.length > 0
                            curr_door = door_queue.pop
                            #if !(visited_door[curr_door])
                                visited_door[curr_door] = true
                                puts "*******"
                                puts door_queue
                                puts level_queue
                                puts "**********"
                                g.add_edges(level_nodes[curr], door_nodes[curr_door])
                                door_pointer = @doors.find(curr_door)
                                next_levels = JSON.parse(door_pointer.next_levels)
                                next_levels.each do |level|
                                    if !visited_level[level.to_i]
                                        level_queue.push(level.to_i)
                                    end
                                    puts "*******~~~~~~~"
                                    puts level_queue
                                    puts curr_door
                                    puts "**********~~~~`"
                                    if !level_door_visit[[level.to_i, curr_door]]
                                        g.add_edges(door_nodes[curr_door], level_nodes[level.to_i])
                                        level_door_visit[[level.to_i, curr_door]] = true
                                    end
                                end
                            #end
                        end
                    end
                end
            else
                @errors.push("No starting level")
                valid = false
            end
            g.output( :png => "app/assets/images/hello_world.png" )  
            @game.graph_image.attach(io: File.open("app/assets/images/hello_world.png"), filename: "hello_world.png")
            t = GraphViz::Theory.new( g )
            g.each_node do |name, node|
              if t.degree(node) == 0
                @errors.push("Unconnected level: #{name}")
                valid = false
              end
            end
            hash = Hash.new
            hash[:errors] = @errors
            hash[:valid] = valid
            return hash
        end     
    end
end       

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  include UsersHelper
  include SessionsHelper


  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
    render "new"
  end

  # GET /games/new
  def new
    @game = Game.new
  end


  
  def all
    @games = Game.search(params[:search]).where.not(start_level_id: nil).where.not(admin_id: session['user_id']).paginate(:per_page => 20,:page => params[:page]).order(:popularity)
    @self=Game.search(params[:search]).where(admin_id: session['user_id']).paginate(:per_page => 20,:page => params[:page])
    render "all"
  end
  def barload
    @games = Game.search(params[:search]).where.not(start_level_id: nil).where.not(admin_id: session['user_id']).paginate(:per_page => 20,:page => params[:page])
    @self=Game.search(params[:search]).where(admin_id: session['user_id']).paginate(:per_page => 20,:page => params[:page])
    render layout: false
  end
  def startinglevel
    @game_id = params[:game_id]
    @level_id = params[:level_id]
    @game = Game.find_by(id: @game_id)
    @game.start_level_id = @level_id
    if(@game.save)
      flash[:success] = "Starting level set"
    else
      flash[:fail] = "Failed to set starting level"
    end
    render 'levels/designatestart', game_id: @game_id
  end


  # GET /games/1/edit
  def edit
  end
 
  def review
    @valid = valid()
  end
  require 'graphviz/theory'
  def valid
    @game_id = params[:game_id]
    @game = Game.find_by(id: @game_id)
    @start_level_id = @game.start_level_id
    @levels = Level.where(game_id: @game_id)
    @doors = Door.where(game_id: @game_id)
    hash = Games::Graph.new(@game, @start_level_id, @levels, @doors, @errors).valid
    valid = hash[:valid]
    @errors = hash[:errors]
    valid
  end 

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.admin_id = session['user_id']
    @game.popularity = 1
    if @game.save
        flash[:success] = "Great! New game created, let's add some levels to the game."
        #puts @game.id 
        redirect_to leveldashboard_url(@game.id)
    else
        render "new"
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:game_name, :start_level_id, :description, :admin_id, :image_url, :popularity, :game_image)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_allGames.html.erb
<div class="tab-pane" id="2">
          <div class="gs-row-3">
            <h1>Community Games</h1>
          </div>

          <div class="gs-row-2">
            <% @games.each do |game| %>
            <div class="gs-row-2-col">
                <div class="gs card">
                  <% if game.game_image.blank? %>
                    <%= image_tag("defaultgame.png", :height =>"180", :width => "260") %>
                  <% else %>
                      <%= image_tag(game.game_image, :height =>"180", :width => "260") %>
                  <% end %>
                  <div class="gs card-body">
                    <h3 class="gs card-title"><%= game.game_name %></h3>
                    <% if game.description.blank? %>
                      <h4 class="gs card-text">No description</h4>
                    <% else %>
                      <h4 class="gs card-text"><%= game.description %></h4>
                    <% end %>
                    <%= link_to "Play", initiate_url(game.id), class: "btn-card" %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
				</div>
<%= will_paginate @games%>

app/views/games/_form.html.erb
<%= stylesheet_link_tag 'creategame' %>
<html>
  <head>
    <title>Create Your Game</title>
  </head>

  <body>
    <div class="cg-container">
      <div class='cg-row-1'>
        <h1>Create a New Game</h1>
      </div>
      <br>
      
      <div>
        <%= form_with(model: game, local: true) do |form| %>
          <!-- Validation check -->
          <% if game.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>
              <ul>
                <% game.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <!-- Input fields-->
          <div>
            <%= form.label 'Enter game name:', class: 'game-form-control-label'%>
            <%= form.text_field :game_name, class: 'game-form-control-field' %>
          </div>
          <div>
            <%= form.label 'Write a brief description of this game:', class: 'game-form-control-label'%>
            <%= form.text_field :description, class: 'game-form-control-field'  %>
          </div>
          <div>
            <%= form.label 'Upload a game image:', class: 'game-form-control-label'%>
            <%= form.file_field :game_image, class: 'game-form-control-field'%>
          </div>
          <!-- Submit Button-->
          <div>
            <%= form.submit "Create This Game", class: "btn-creategame" %>
          </div>
        <% end %>
      </div>

    </div>

  </body>
<html>

app/views/games/_userGames.html.erb
<div class="tab-pane active" id="1">
          <div class="gs-row-1">
            <h1>Your Games</h1>
          </div>

          <div class="gs-row-2">

            <div class="gs-row-2-col">
              <div class="gs card">
                <div class="gs card-body">
                  <%= link_to(image_tag("plussign.png", :height =>"250", :width => "250", :class=>"cancelhoverEXP"), creategame_path)%>
                </div>
              </div>
            </div>
            
            <% @self.each do |game| %>
            <div class="gs-row-2-col">
              <div class="gs card">
                <% if game.game_image.blank? %>
                  <%= image_tag("defaultgame.png", :height =>"180", :width => "260")%>
                <% else %>
                    <%= image_tag(game.game_image, :height =>"180", :width => "260")%>
                <% end %>
                <div class="gs card-body">
                  <h3 class="gs card-title"><%= game.game_name %></h3>
                  <% if game.description.blank? %>
                    <h4 class="gs card-text">No description</h4>
                  <% else %>
                    <h4 class="gs card-text"><%= game.description %></h4>
                  <% end %>
                  <% if game.start_level_id!=nil%>
                  <%= link_to "Play", initiate_url(game.id), class: "btn-card" %>
                  <%end%>
                  <%= link_to "Edit", leveldashboard_url(game.id), class: "btn-card" %>
                </div>
              </div>
            </div>
            <% end %>
          </div>
        </div>

app/views/games/all.html.erb
<%= stylesheet_link_tag 'gamecenter' %>
    <title>Game Center</title>
    <div class="search-c">
      <input type="search" id="search" placeholder="Search for the game you want:" />
    </div>
    <div id="exTab2" class="gs-container">	
    	
      <ul class="nav nav-tabs">
         <li class="active">
          <a href="#1" data-toggle="tab">Your Games</a>
        </li>
        <li >
          <a href="#2" data-toggle="tab">Community Games</a>
        </li>
      </ul>

			<div class="tab-content">
			  <%= render "userGames"%>
			   <!-- End of id='1'-->
			<%= render "allGames"%>
				<!-- End of id='2'-->

			</div> <!-- tab content class-->
    </div> <!-- gs-container class-->
<%= javascript_pack_tag 'game.js' %>

app/views/games/barload.html.erb
<%= render "userGames", layout: false%>
<!-- End of id='1'-->
<%= render "allGames", layout: false%>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Game name</th>
      <th>Start level</th>
      <th>Description</th>
      <th>Admin</th>
      <th>Image url</th>
      <th>Popularity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.game_name %></td>
        <td><%= game.start_level_id %></td>
        <%= image_tag(game.game_image) %>

        <td><%= game.description %></td>
        <td><%= game.admin_id %></td>
        <td><%= game.image_url %></td>
        <td><%= game.popularity %></td>
        <%= image_tag(game.game_image) %>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<%= render 'form', game: @game %>

app/views/games/review.html.erb
<%= stylesheet_link_tag 'review_game' %>
<div class= "graph-container">
    <div class= "title">
        Review your game
    </div>
    <div class= "graph-body">
        Start Level:
        <div class="graph-body-text">
            <% if @game.start_level_id.nil? %>
                You should set a start level:
                <%= link_to("designate start", designatestart_path(@game.id)) %>
            <% else %>
                Your start level is: 
                <% @start_level = Level.find_by(id: @game.start_level_id) %>
                <%= @start_level.name %>
                <br>
                <%= image_tag(@start_level.level_image, :height =>"180", :width => "260") %>
            <% end %>
        </div>
        <br> <br>
    </div>
    <div class="graph-body">
        Review your level structure:
        <div class="graph">
            <%= image_tag(@game.graph_image, :class => "img_graph")%> 
        </div>
        <br>
    </div>
    <%if @valid %>
        <div class='graph-body'>
			<%= link_to "Finish!", allgames_path, class: "btn-finishgame" %>
        </div>
    <% else %>
       <div class='error-finish'>
            You must finish creating the game before you can continue
        </div>
        <div class='errors'>
            <% @errors.each do |error| %>
                <%= error %>
                <br>
            <%end %>
        </div>
    <% end %>
    <br>
    <br>
    <div class='graph-body'>
	    <%= link_to "Return to dashboard", leveldashboard_path(@game.id), class: "btn-dashboard" %>
    </div>
</div>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game name:</strong>
  <%= @game.game_name %>
</p>

<%= image_tag(@game.game_image) %>
<p>
  <strong>Start level:</strong>
  <%= @game.start_level_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @game.admin_id %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @game.image_url %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @game.popularity %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>