config/routes.rb
Rails.application.routes.draw do
  resources :topics
  resources :messages
  resources :doors
  resources :event_instances
  resources :events
  resources :heroes
  resources :levels
  resources :games
  resources :heroes
  resources :packages
  resources :doors
  resources :users
  resources :gamestates
  resources :sessions
  get  '/gamestate', to: 'gamestates#save'
  get 'main/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'main#index'
  #post 'levels/doors', to: 'levels#doors'
  get   'level-doors/:id', to: 'levels#doors'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'


  get '/event_instances/:id/:choice', to: 'event_instances#show'

  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/gamestates/reset/:id', to: 'gamestates#reset'
  get '/gamestates/partial/:id', to: 'gamestates#partial'
  get '/games', to: 'games#index'
  get '/discussion', to: 'messages#discussion'
  post '/discussion', to: 'message#create'
  get '/addtopic', to: 'topics#new'
  get '/topic/:id', to: 'topics#show', as: 'joindiscuss'
  get '/publishedgames', to: 'games#published'
  get '/doors/open/:id', to: 'doors#open'
  #game creation
  get '/creategame', to: 'games#new'
  get '/allgames', to: 'games#all'
  get '/barload', to: 'games#barload'
  get '/addlevel/:game_id' , to: 'levels#new', as: 'addlevel'
  get '/addevent/:game_id' , to: 'events#new', as: 'addevent'
  get '/adddoor/:game_id' , to: 'doors#new', as: 'adddoor'
  get '/addhero/:gamestate_id' , to: 'heroes#new', as: 'addhero'

  get 'editevent/:game_id/:id', to: 'events#edit', as: 'editevent'
  get 'editlevel/:game_id/:level_id', to: 'levels#organizeevents', as: 'editlevel'
  get 'editdoor/:game_id/:id', to: 'doors#edit', as: 'editdoor'

  get '/assigneventforone/:game_id/:level_id', to: 'levels#assigneventforone', as: 'assigneventforone'
  get '/queueevent/:game_id/:level_id/:event_id', to: 'levels#queueevent', as: 'queueevent'
  get '/dequeueevent/:game_id/:level_id', to: 'levels#dequeueevent', as: 'dequeueevent'

  get '/assigndoorforone/:game_id/:level_id', to: 'levels#assigndoorforone', as: 'assigndoorforone'
  get '/queuedoor/:game_id/:level_id/:door_id', to: 'levels#queuedoor', as: 'queuedoor'
  get '/dequeuedoor/:game_id/:level_id', to: 'levels#dequeuedoor', as: 'dequeuedoor'

  get '/assignlevelforone/:game_id/:door_id', to: 'doors#assignlevelforone', as: 'assignlevelforone'
  get '/queuelevel/:game_id/:door_id/:level_id', to: 'doors#queuelevel', as: 'queuelevel'
  get '/dequeuelevel/:game_id/:door_id', to: 'doors#dequeuelevel', as: 'dequeuelevel'

  #get '/assigneventforall/:game_id', to: 'levels#assigneventforall', as: 'assigneventforall'
  get '/creategamelogic/:game_id', to: 'levels#creategamelogic', as: 'creategamelogic'
  get '/organize/:game_id' , to: 'levels#organize', as: 'organizelevel'
  get 'designatestart/:game_id', to: 'levels#designatestart', as: 'designatestart'
  get '/levels/dashboard/:game_id', to: 'levels#dashboard', as: 'leveldashboard'
  get '/startinglevel/:game_id/:level_id', to: 'games#startinglevel', as: 'startinglevel'

  get '/initiatehero/:game_id', to: 'gamestates#initiate', as: 'initiate'

  #search routets

  post '/searchtopic', to: 'topics#search'
  get '/searchtopic', to: 'topics#search'

  get '/review/:game_id', to: 'games#review', as: 'review'

end

app/models/level.rb
class Level < ApplicationRecord
    has_one_attached :level_image
    belongs_to :game
    has_many :events
    validates :name, presence: true, length: { maximum: 50 }
    has_one_attached :level_image
    
    def attachment_url
        if self.level_image.attached?
          Rails.application.routes.url_helpers.rails_blob_path(self.level_image, only_path:true)
        else
          nil
        end
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]
  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
  end

  def ids_to_events lev
    @events = Array.new
    if(lev.event_id.to_s.strip.length != 0)
      event_ids = JSON.parse(lev.event_id)
      event_ids.each do 
        |event_id| event = Event.find_by(id: event_id)
        @events.push(event)
      end
    end
    @events
  end
  helper_method :ids_to_events

  def doors_to_names lev
    @names = Array.new
    if(lev.doors.to_s.strip.length > 2)
      door_ids = JSON.parse(lev.doors)
      door_ids.each do 
        |door_id| door = Door.find_by(id: door_id)
        @names.push(door.name)
      end
    end
    @names
  end
  helper_method :doors_to_names

  def creategamelogic
    @game_id = params[:game_id]
  end

  def queueevent
    @game_id = params[:game_id]
    @level_id = params[:level_id]
    @event_id = params[:event_id]
    curr_level = Level.find_by(id: @level_id)
    curr_event_ids = Array.new
    len = curr_level.event_id.to_s.strip.length
    
    #because the default JSON string is "[]"
    if(len > 2)
      curr_event_ids = JSON.parse(curr_level.event_id)
    end
    curr_event_ids.push(@event_id)
    curr_level.event_id= curr_event_ids.to_json
    event = Event.find_by(id: @event_id)
    if(curr_level.save)
      flash[:success] = "Great, " + event.name + " was added to the list"  
    end
    render 'assigneventforone'
  end

  def dequeueevent
    @game_id = params[:game_id]
    @level_id = params[:level_id]
    @pointer = params[:counter]
    curr_level = Level.find_by(id: @level_id)
    len = curr_level.event_id.to_s.strip.length
    
    #because the default JSON string is "[]"
    if(len <= 2)
      flash[:fail] = "No events to remove"
    else
      curr_event_ids = JSON.parse(curr_level.event_id)
      curr_event = curr_event_ids.delete_at(@pointer.to_i)
      curr_event = Event.find_by(id: curr_event)
      curr_level.event_id= curr_event_ids.to_json
      if(curr_level.save)
        flash[:success] = "Great, " + curr_event.name + " was removed from the list"  
      end
    end
    render 'assigneventforone'

  end
  
  def dashboard
    @game_id= params[:game_id]    
  end
  # GET /levels/new
  def new
    @level = Level.new
    @level.game_id = params[:game_id]
  
  end

  # GET /levels/1/edit
  def edit
  end
  
  def doors
    if params.has_key? "id"
      g=Gamestate.find_by(id: params['id'])
      l=Level.find_by(id: g.level_id)
      arr=[]
      if l.doors.length>0
        arr=JSON.parse(l.doors)
      end
      if arr.length>0
        i=1
        w="id='#{arr[0]}'"
        while i<arr.length
          w+=" or id='#{arr[i]}'"
          i+=1
        end
        ar=[1]
        d=Door.where(w)
        render json: d
      else
        render json: [].to_json
      end
    end
  end

  def designatestart
    @game_id = params['game_id']
    @game = Game.find_by(id: @game_id)
  end
  def organizeevents
    @level = Level.find_by(id: params['level_id'])
    @game = Game.find_by(id: params['game_id'])
    render 'edit'
  end
  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)
    @events = Array.new
    @level.event_id = @events.to_json
    #@level.game = Game.find(level_params[:game_id])
    #@level.image = url_for(@level.level_image)
    if(!@level.level_image.attached?)
      @level.level_image.attach(io: File.open("app/assets/images/samplegame2.jpg"), filename: "samplegame2.jpg")
    end
    @level.image = @level.level_image.service_url
   
    doors = Array.new
    @level.doors = doors.to_json
    if @level.save
        flash[:success] = "Great! New level created."
        if params[:commit] == 'Finish This Level'
          redirect_to leveldashboard_url(@level.game_id)
        else
          redirect_to addlevel_url(@level.game_id)
        end
      else
        render "new"
      end
end
  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    # @level.image = url_for(@level.level_image)
    if(!@level.level_image.attached?)
      @level.level_image.attach(io: File.open("app/assets/images/samplegame2.jpg"), filename: "samplegame2.jpg")
    end
    @level.image = @level.level_image.service_url
    if @level.update(level_params)
        if params[:commit] == 'Save & Finish'
          redirect_to leveldashboard_url(@level.game_id)
        elsif params[:commit] == 'Add events'
            redirect_to assigneventforall_path(@level.game_id)
        else
          redirect_to addlevel_url(@level.game_id)
        end
    else 
      render "edit"
    end
  end
  def assigneventforall
    @game_id = params['game_id']
  end
  def assigneventforone
    @game_id = params['game_id']
    @level_id = params['level_id']
  end
  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name, :event_id, :game_id, :doors, :description, :level_image, :image)
    end
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/views/levels/_form.html.erb
<%= stylesheet_link_tag 'createlevel' %>
<html>
  <head>
    <title>Create Level</title>
  </head>

  <body>
  <div class= 'cl-container'>
      <div class='cl-row-1'>
        <h1>Create a New Level</h1>
      </div>
      <br>
      
      <div>
        <%= form_with(model: level, local: true) do |form| %>
          <% if level.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(level.errors.count, "error") %> prohibited this level from being saved:</h2>
            <ul>
              <% level.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
          <% end %>

        <div>
          <%= form.hidden_field :game_id, :value => params[:game_id] %>
        </div>
        <div>
          <%= form.label:name, "Enter level name:", class: 'level-form-control-label' %>
          <%= form.text_field :name, class: 'level-form-control-field'%>
        </div>
        <div>
          <%= form.label:description, "Write a brief description of this level:", class: 'level-form-control-label' %>
          <%= form.text_field :description ,class: 'level-form-control-field'%>
        </div>
        <div>
            <%= form.label:level_image, "Upload a level image:", class: 'level-form-control-label' %>
            <%= form.file_field :level_image ,class: 'level-form-control-field' %>
        </div>
        <div>
          <%= form.submit "Finish This Level", class: "btn-createlevel" %>
        </div>
        
        <div>
          <%= form.submit "Create Next Level", class: "btn-createlevel" %>
        </div>
        <% end %>
     </div>  <!-- form class -->
  </div> <!-- container class -->
  </body>
<html>

app/views/levels/assigndoorforone.html.erb
Assign doors to this level:
<br>
<% @level = Level.find_by(id: @level_id) %>


Available Doors:
<% @doors = Door.where(game_id: @game_id) %>
<% @door_names = Array.new %>
<% if !@doors.nil? %>
    <% @doors.each do |door| %>
        <%= link_to door.name, queuedoor_path(@game_id, @level_id, door.id) %>
        <% @door_names.push(door.name) %>
        <%= door.result %>
    <% end %>
    <% @level.name %>

<br>
<% else %>
        You don't have any doors
        <%= link_to 'Go back and make some doors', adddoor_path(@game_id) %>
        <%= link_to 'Back to the dashboard', leveldashboard_path(@game_id) %>
<% end %>
<% @names = doors_to_names(@level) %>
    Doors currently assigned to this level: 
    <br>
    <% @names.each do |name| %>
        <%= name %>
        <br>
<% end %>
    
<br> 
<%= link_to "Remove the last door", dequeuedoor_path(@game_id, @level_id) %>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<%= link_to 'Finish adding doors for this level and choose a different level', creategamelogic_path(@game_id) %>

app/views/levels/assigneventforall.html.erb
<h1> Assign events to levels </h1>
Here are the levels that need events assigned
<% @unassigned_levels = Level.where(game_id: @game_id, event_id: [nil, "[]", ""]) %>
<% @assigned_levels = Level.where(game_id: @game_id).where.not(event_id: [nil, "[]", ""]) %>
<br>
Levels with assigned events
<br> 
<% @assigned_levels.each do |level| %>
        <% level %>
        <%= link_to level.name, assigneventforone_path(@game_id, level.id) %>
        <% if (level.level_image.attached?) %>
                <%= link_to image_tag(level.level_image, :height =>"47", :width => "70"), assigneventforone_path(@game_id, level.id)  %>
        <% end %>
<% end %>
<br>
Levels without assigned events
<% @unassigned_levels.each do |level| %>
        <% level %>
        <%= link_to level.name, assigneventforone_path(@game_id, level.id) %>
        <% if (level.level_image.attached?) %>
                <%= link_to image_tag(level.level_image, :height =>"47", :width => "70"), assigneventforone_path(@game_id, level.id)  %>
        <% end %>
<% end %>
<br>
<%= link_to 'Back to the dashboard', leveldashboard_path(@game_id) %>

<br>

app/views/levels/assigneventforone.html.erb
<%= stylesheet_link_tag 'assignevent' %>

<html>
    <head>
        <title> Assign Events</title>
    </head>

    <body>
        <div class="aefo-container">
            <div class="aefo-row-1">
                <h1>Event Assignment</h1>
                <h2>Available Events: </h2>
                <h3>Click to add to the list </h3>
            </div>

            <div class="aefo-row-2">
            <% @level = Level.find_by(id: @level_id) %>
                <% @events = Event.where(game_id: @game_id) %>
                <% @event_names = Array.new %>
                <% if !@events.nil? %>
                    <% @events.each do |event| %>
                        <div class="aefo-row-2-col">
                        <div class="aefo card shadow-lg rounded">
                            <% if event.event_image.blank? %>
                                <%= link_to event.name, queueevent_path(@game_id, @level_id, event.id)%>
                            <% else %>
                                <%= link_to(image_tag(event.event_image, :height =>"120", :width=> "110"), queueevent_path(@game_id, @level_id, event.id)) %>
                            <% end %>
                            <div class="aefo card-body">
                                <h3 class="aefo card-title"><%= event.name%></div>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <h2>You do not have any events </h2>
                    <%= link_to 'Go back and make some events', addevent_path(@game_id) %>
                    <%= link_to 'Back to the dashboard', leveldashboard_path(@game_id) %>
                <% end %>
            </div>

            <div class="aefo-row-3">
                <h2>Current Assignment(order from left to right): </h2>
                <h3>Click to remove from the list </h3>
            </div>

            <div class="aefo-row-2">
                <% @events = ids_to_events(@level) %>
                <% @counter = 0 %>
                <% @events.each do |event| %>
                <div class="aefo-row-2-col">
                    <div class="aefo card">
                        <%= link_to(image_tag(event.event_image, :height =>"120", :width => "110", :class=>"cancelhoverEXP"), dequeueevent_path(@game_id, @level_id, @counter))%>
                        <div class="aefo card-body">
                            <h4 class="aefo card-text"> <%= event.name %></h4>
                        </div>
                    </div>
                </div>
                <% @counter+= 1 %> 
                <% end %>


            
            <%= link_to 'Back to dashboard', leveldashboard_path(@game_id), :class=>"btn-returndash"%>
           

        </div> <!-- aefo container class end-->
    </body>
</html>

app/views/levels/creategamelogic.html.erb
 Step 1: Create some doors:
<%= link_to 'Add doors',adddoor_url(@game_id) %>
<br>
Edit existing doors:
<% doors = Door.where(game_id: @game_id) %>
<% doors.each do |door| %>
        <%= link_to door.name, editdoor_path(@game_id, door.id)%>
<% end %>

<br>
<br>
Step 2: Connect doors to their next levels
<% doors.each do |door| %>
        <%=  link_to door.name, assignlevelforone_path(@game_id, door.id)%>
<% end %>
<br>
<br>
Step 3: Assign doors to each level

<% levels = Level.where(game_id: @game_id) %>
<% levels.each do |level| %>
        <%=  link_to level.name, assigndoorforone_path(@game_id, level.id)%>
<% end %>
<br>
<%= link_to 'Back to dashboard', leveldashboard_path(@game_id) %>

app/views/levels/dashboard.html.erb
<%= stylesheet_link_tag 'dashboard' %>

<body>
	<div class="overall-container">
		<nav class='dash-navbar'>
			<ul>
				<li><a href="#section1">Instruction</a><li>
				<li><a href="#section2">Step 1</a><li>
				<li><a href="#section3">Step 2</a><li>
				<li><a href="#section4">Step 3</a><li>
				<li><a href="#section5">Step 4</a><li>
				<li><a href="#section6">Step 5</a><li>
				<li><a href="#section7">Review</a><li>
			</ul>
		</nav>

		<section id='section1'>
			<h1>Dashboard</h1>
			<h2>This is the dashboard for your game creation</h2>
			<br>
			<h2>Follow these EASY five steps to complete your game!</h2>
			<br>
			<br>
			<div class="db-welcome-container">
				<div class="db-welcome-row">
					<div class='db-welcome-col'>
						<a href="#section2">
						<div class="db-welcome card shadow-lg rounded">
							<%= image_tag("one.png", :height =>"180", :width => "200")%>
							<div class="db-welcome card-body">
								<h5 class="db-welcome card-title"> Add <br> Levels </h5>
								<p class="db-welcome card-text">
								Create some levels as the cornerstones of your game. They are the background environment of your game playing experience.
								</p>
							</div>
						</div>
						</a>
					</div>
					<div class='db-welcome-col'>
						<a href="#section3">
						<div class="db-welcome card shadow-lg rounded">
							<%= image_tag("two.png", :height =>"180", :width => "200") %>
							<div class="db-welcome card-body">
								<h5 class="db-welcome card-title"> Add <br> Events </h5>
								<p class="db-welcome card-text">
								Events are the challenges you will face in each level, including two types: direct and fight.
								</p>
							</div>
						</div>
						</a>
					</div>
					<div class='db-welcome-col'>
						<a href="#section4">
						<div class="db-welcome card shadow-lg rounded">
							<%= image_tag("three.png", :height =>"180", :width => "200") %>
							<div class="db-welcome card-body">
								<h5 class="db-welcome card-title"> Assign <br> Events </h5>
								<p class="db-welcome card-text">
								You mayput any number of events inside of each level. Assignment order represent the order events will appear in each level.
								</p>
							</div>
						</div>
						</a>
					</div>
					<div class='db-welcome-col'>
						<a href="#section5">
						<div class="db-welcome card shadow-lg rounded">
							<%= image_tag("four.png", :height =>"180", :width => "200") %>
							<div class="db-welcome card-body">
								<h5 class="db-welcome card-title"> Add<br> Doors </h5>
								<p class="db-welcome card-text">
								Doors are the logic backbone of your game. For each door, set the requirement and connect it with its previous level and next level.
								</p>
							</div>
						</div>
						</a>
					</div>

					<div class='db-welcome-col'>
						<a href="#section6">
						<div class="db-welcome card shadow-lg rounded">
							<%= image_tag("five.png", :height =>"180", :width => "200") %>
							<div class="db-welcome card-body">
								<h5 class="db-welcome card-title"> Designate Start </h5>
								<p class="db-welcome card-text">
								Select a starting level for you game from your existing levels. Your game is ready to play!
								</p>
							</div>
						</div>
						</a>
					</div>
				</div>
			</div>
		</section>

		<section id='section2'>
			<div class='sectionhead'>
				<h1>Level Creation</h1>
			</div>
			<div class='db-row-list'>
				<%= link_to(image_tag("plussign.png", :height =>"90", :width => "90", :class=>"cancelhover"), addlevel_path(@game_id))%>
				<% levels = Level.where(game_id: @game_id) %>
				<% levels.each do |level| %>
					<% if (level.level_image.attached?) %>
						<%= link_to image_tag(level.level_image, :height =>"90", :width => "90"), editlevel_path(@game_id, level.id)  %>
					<% else %>
						<%= link_to level.name, editlevel_path(@game_id, level.id) %>
					<% end %>
				<% end %>
			</div>
		</section>

		<section id='section3'>
			<h1>Event Creation</h1>
			<div class='db-row-list'>
				<%= link_to(image_tag("plussign.png", :height =>"90", :width => "90"), addevent_path(@game_id)) %>
				<% events = Event.where(game_id: @game_id) %>
				<% events.each do |event| %>
					<% if (event.event_image.attached?) %>
						<%= link_to image_tag(event.event_image, :height =>"90", :width => "90"), editevent_url(@game_id, event.id)  %>
					<% else %>
						<%=  link_to event.name, editevent_url(@game_id, event.id) %>
					<% end %>
				<% end %>
			</div>
		</section>

		<section id='section4'>
			<h1> Event Assignment</h1>
			<div class='db-assign-container'>
				<% @unassigned_levels = Level.where(game_id: @game_id, event_id: [nil, "[]", ""]) %>
				<% @assigned_levels = Level.where(game_id: @game_id).where.not(event_id: [nil, "[]", ""])%>

				<div class='db-assign-col'>
				<h4>Levels Assigned</h4>
				<% @assigned_levels.each do |level| %>
					<% if (level.level_image.attached?) %>
						<%= link_to image_tag(level.level_image, :height =>"90", :width => "90"), assigneventforone_path(@game_id, level.id)  %>
					<% else %>
						<%= link_to level.name, assigneventforone_path(@game_id, level.id) %>
					<% end %>
				<% end %>
				</div>

				<div class='db-assign-col'>
				<h4>Levels Unassigned</h4>
				<% @unassigned_levels.each do |level| %>
					<% if (level.level_image.attached?) %>
						<%= link_to image_tag(level.level_image, :height =>"90", :width => "90"), assigneventforone_path(@game_id, level.id)  %>
					<% else %>
						<%= link_to level.name, assigneventforone_path(@game_id, level.id) %>
					<% end %>
				<% end %>
				</div>
			</div>
		</section>

		<section id='section5'>
			<h1>Door Creation</h1>
			<div class='db-row-list'>
				<%= link_to(image_tag("plussign.png", :height =>"90", :width => "90"), adddoor_path(@game_id)) %>
				<% doors = Door.where(game_id: @game_id) %>
				<% doors.each do |door| %>
					<% if (door.door_image.attached?) %>
						<%= link_to image_tag(door.door_image, :height =>"90", :width => "90"), editdoor_url(@game_id, door.id)  %>
				<% else %>
						<%= link_to door.name, editdoor_url(@game_id, door.id) %>
					<% end %>
				<% end %>
			</div>
		</section>

		<section id='section6'>
			<h1>Start Designation</h1>
			<div class='db-row-list'>
				<%= link_to(image_tag("plussign.png", :height =>"90", :width => "90"), designatestart_path(@game_id)) %>
				<% @game = Game.find_by(id: @game_id) %>
				<% @start_level = Level.find_by(id: @game.start_level_id) %>
				<% if(!@start_level.nil?) %>
					<% if(@start_level.level_image.attached?) %>
						<%= image_tag(@start_level.level_image, :height =>"90", :width => "90") %>
					<% end %>
				<% end %>
			</div>
		</section>

		<section id='section7'>
			<%= link_to "Review game", review_path(@game_id), class: "btn-finishgame" %>
		</section>

	</div>
<body>

app/views/levels/designatestart.html.erb
<%= stylesheet_link_tag 'designatestart' %>
<title> Designate Start </title>

<div class="ds-container">
        <h1> Designate your starting level </h1>
        <h2> Click on the level to designate </h2>
        <% levels = Level.where(game_id: @game_id).order(:id) %>
        <% @game = Game.find(@game_id) %>
        <% levels.each do |level| %>
                <div class= "<%= if @game.start_level_id == level.id then "bordered" else "internal" end%> card">
                        <div>
                                <% if level.level_image.blank? %>
                                        <%= link_to level.name, startinglevel_path(@game_id, level.id)%>
                                <% else %>
                                        <%= link_to(image_tag(level.level_image, :height =>"180", :width => "260"), startinglevel_path(@game_id, level.id)) %>
                                <% end %>
                        </div>
                        <div class="card-body">
                                <h3 class="card-title"><%= level.name %></h3>
                        </div>
                </div>
        <% end %>
        <br>
        <br>
        <%= link_to "Back to dashboard", leveldashboard_path(@game_id), :class=> "btn-returndash"%>

</div>

app/views/levels/doors.html.erb
<h1> Doors </h1>
<b>
<%= "Your available doors are: " %>
<% @resultArray.each do |door| %>
    <%= door%>
    <%= ", "%>
<% end %>
<%= "which door would you like to take?" %>
</b>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>
<%= render 'form', level: @level %>

<%= link_to 'Back to the dashboard', leveldashboard_path %>

<% puts @level.game_id %>
<% puts @level.id %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Levels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Event</th>
      <th>Game</th>
      <th>Doors</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @levels.each do |level| %>
      <tr>
        <td><%= level.name %></td>
        <td><%= level.event_id %></td>
        <td><%= level.game_id %></td>
        <td><%= level.doors %></td>
        <td><%= level.description %></td>
        <td><%= level.image %></td>
        <td><%= link_to 'Show', level %></td>
        <td><%= link_to 'Edit', edit_level_path(level) %></td>
        <td><%= link_to 'Destroy', level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Level', new_level_path %>

app/views/levels/new.html.erb
<%= stylesheet_link_tag 'createlevel' %>

<body>
    <div class='newlevelpage'>
        <%= render 'form', level: @level %>
        <div class='returndashclass'>
            <%= link_to 'Back to Dashboard', leveldashboard_path(@level.game_id), :class=>"btn-createlevel"%>
        </div>
    </div>
</body>

app/views/levels/organizeevents.html.erb
<%= render 'show' %>

app/views/levels/organizelevelform.html.erb
<p id="notice"><%= notice %></p>
 
<h1>Organize Game Levels</h1>
 
<h2>
<%= link_to 'You current have these levels', levels_path %>
</h2>
 
<h2>
<%= link_to 'Add more levels', addlevel_path %>
</h2>
 
<h2>Add logic/doors to your levels</h2>
 
 

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @level.name %>
</p>

<p>
  <strong>Event:</strong>
  <%= @level.event_id %>
</p>

<p>
  <strong>Game:</strong>
  <%= @level.game_id %>
</p>

<p>
  <strong>Doors:</strong>
  <%= @level.doors %>
</p>

<p>
  <strong>Description:</strong>
  <%= @level.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @level.image %>
</p>

<%= link_to 'Edit', edit_level_path(@level) %> |
<%= link_to 'Back', levels_path %>